services:
  - type: web
    name: tracely-ai
    env: python
    repo: https://github.com/Heregaurav/Tracely-AI
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11 # Specify your version here